name: Frontend CI

on:
  push:
    branches:
      - build-and-deploy
      - nmaliset
      - reddyve
      - schennoj
      - shosinha

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    - name: Using create-react-app
      uses: actions/setup-node@v3
    - run: npm run frontend
